services:
  - type: web
    name: usina-api
    env: python
    plan: free
    region: brazil  # você pode mudar a região se quiser
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10