services:
  - type: web
    name: usina-api
    env: python
    plan: free
    region: brazil  # você pode mudar a região se quiser
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10