services:
  - type: web
    name: usina-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app:app"
    plan: free
    envVars:
      - key: ENV
        value: production